Repository helm/chartmuseum, pull requests merged in 2019-12, with the labels that each got.

#284 feat(router): add support for CORS Access-Control-Allow-Origin header
  cmd/chartmuseum/main.go
  pkg/chartmuseum/router/router.go
  pkg/chartmuseum/server.go
  pkg/config/vars.go
Labels: ok-to-test, size/L

#287 update helm to v2.16.1
  go.mod
  go.sum
  scripts/setup_test_environment.sh
Labels: size/S

#291 update gopkg.in/yaml.v2 version to v2.2.7
  go.mod
  go.sum
Labels: size/XS

#292 update alpine base image
  Dockerfile
Labels: size/XS

#294 update to helm v3
  Makefile
  go.mod
  go.sum
  pkg/chartmuseum/server/multitenant/api.go
  pkg/chartmuseum/server/multitenant/cache.go
  pkg/repo/chart.go
  pkg/repo/chart_test.go
  pkg/repo/index.go
  pkg/repo/index_test.go
  pkg/repo/provenance.go
Labels: ok-to-test, size/L
