Repository helm/chartmuseum, pull requests merged in 2019-09, with the labels that each got.

#265 add using yaml file example to readme
  README.md
Labels: size/S

#267 fix transformLogcArgs gin panic
  pkg/chartmuseum/logger/logger.go
Labels: size/XS

#268 fix ChartVersion parse conflict
  pkg/repo/chart.go
  pkg/repo/chart_test.go
Labels: size/M
