Repository helm/chartmuseum, pull requests merged in 2019-03, with the labels that each got.

#214 Fix for multitenant repos with name api*
  Makefile
  cmd/chartmuseum/main.go
  cmd/chartmuseum/main_test.go
  go.mod
  go.sum
  pkg/chartmuseum/logger/logger_test.go
  pkg/chartmuseum/router/match.go
  pkg/chartmuseum/router/match_test.go
  pkg/chartmuseum/router/middleware.go
  pkg/chartmuseum/router/router.go
  pkg/chartmuseum/router/router_test.go
  pkg/chartmuseum/server.go
  pkg/chartmuseum/server/multitenant/api.go
  pkg/chartmuseum/server/multitenant/cache.go
  pkg/chartmuseum/server/multitenant/handlers.go
  pkg/chartmuseum/server/multitenant/index.go
  pkg/chartmuseum/server/multitenant/routes.go
  pkg/chartmuseum/server/multitenant/server.go
  pkg/chartmuseum/server/multitenant/server_test.go
  pkg/chartmuseum/server/multitenant/storage.go
  pkg/repo/chart.go
  pkg/repo/chart_test.go
  pkg/repo/provenance_test.go
  scripts/setup_test_environment.sh
Labels: size/L

#216 Add Gocenter support for go
  Makefile
Labels: size/XS

#217 Add env var GOCACHE
  .codefresh/master.yml
  .codefresh/pr.yml
  Makefile
  scripts/test.sh
Labels: size/S

#218 preserve go-modules between steps and builds
  .codefresh/master.yml
  .codefresh/pr.yml
Labels: size/XS
