Repository helm/chartmuseum, pull requests merged in 2019-01, with the labels that each got.

#204 Fixing bad data issue
  acceptance_tests/helm.robot
  acceptance_tests/lib/ChartMuseum.py
  acceptance_tests/lib/common.py
  pkg/chartmuseum/server/multitenant/api.go
  pkg/chartmuseum/server/multitenant/handlers.go
  pkg/chartmuseum/server/multitenant/server_test.go
  testdata/badcharts/mybadchart/.helmignore
  testdata/badcharts/mybadchart/Chart.yaml
  testdata/badcharts/mybadchart/mybadchart-1.0.0.tgz
  testdata/badcharts/mybadchart/mybadchart-1.0.0.tgz.prov
  testdata/badcharts/mybadchart/templates/pod.yaml
Labels: size/L

#203 Add support for TLS client certificate auth
  README.md
  cmd/chartmuseum/main.go
  pkg/chartmuseum/router/router.go
  pkg/chartmuseum/router/router_test.go
  pkg/chartmuseum/server.go
  pkg/config/vars.go
  testdata/clientauthcerts/ca.key
  testdata/clientauthcerts/ca.pem
  testdata/clientauthcerts/client.key
  testdata/clientauthcerts/client.pem
  testdata/clientauthcerts/server.key
  testdata/clientauthcerts/server.pem
Labels: size/L

#208 Add documentation for S3 compatible services like Minio
  README.md
Labels: size/S

#209 Add step to set credentials for S3 compatible services
  README.md
Labels: size/XS
