Repository helm/chartmuseum, pull requests merged in 2020-07, with the labels that each got.

#346 Add support for Swift V1 Auth
  README.md
  cmd/chartmuseum/main.go
  pkg/config/vars.go
Labels: size/M

#350 Multi architecture container image
  .dockerignore
  .github/workflows/build-docker-images.yml
  Dockerfile
  Dockerfile.arm
  Makefile
Labels: size/L

#345 Allow to bind chartmuseum to a specific interface
  cmd/chartmuseum/main.go
  pkg/chartmuseum/router/router.go
  pkg/chartmuseum/server.go
  pkg/config/vars.go
Labels: size/S
