Repository helm/chartmuseum, pull requests merged in 2020-04, with the labels that each got.

#317 fix broken link to helm chart repository reference doc
  README.md
Labels: size/XS

#319 Fixed broken link to provenance docs
  README.md
Labels: size/XS

#322 chartmuseum: add semver2 validation
  cmd/chartmuseum/main.go
  cmd/chartmuseum/main_test.go
  go.mod
  pkg/chartmuseum/server.go
  pkg/chartmuseum/server/multitenant/api.go
  pkg/chartmuseum/server/multitenant/server.go
  pkg/chartmuseum/server/multitenant/server_test.go
  pkg/config/vars.go
  testdata/badsemver2chart/mybadchart/.helmignore
  testdata/badsemver2chart/mybadchart/Chart.yaml
  testdata/badsemver2chart/mybadchart/templates/pod.yaml
Labels: size/M

#324 Add --log-latency-integer option
  README.md
  cmd/chartmuseum/main.go
  pkg/chartmuseum/router/middleware.go
  pkg/chartmuseum/router/router.go
  pkg/chartmuseum/server.go
  pkg/config/vars.go
Labels: size/L
