Repository helm/chartmuseum, pull requests merged in 2020-11, with the labels that each got.

#382 Update readme steps, missing params in the helm cmd
  README.md
Labels: size/XS

#362 pkg/repo: inject chart metadata(name/version) into storage object
  acceptance_tests/helm.robot
  acceptance_tests/lib/ChartMuseum.py
  go.mod
  go.sum
  pkg/chartmuseum/server/multitenant/cache.go
  pkg/repo/chart.go
  pkg/repo/chart_test.go
  testdata/charts/mychart2/.helmignore
  testdata/charts/mychart2/Chart.yaml
  testdata/charts/mychart2/templates/pod.yaml
Labels: size/L

#390 Add scbizu to OWNERS
  OWNERS
Labels: size/XS

#395 ci: migrate release from docker hub into github container registry
  .github/workflows/release.yml
Labels: size/M
