Repository helm/chartmuseum, pull requests merged in 2021-09, with the labels that each got.

#477 Support Builds for ARM M1 Macs
  Makefile
  scripts/get-chartmuseum
Labels: size/S

#474 mod: bump gin dependency to v1.7.3
  go.mod
  go.sum
Labels: size/XS

#478 ci: make action happy
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  go.mod
  scripts/setup-test-environment.sh
Labels: size/S

#492 Fix duplicate versions for same chart
  pkg/chartmuseum/server/multitenant/handlers.go
  pkg/chartmuseum/server/multitenant/server_test.go
Labels: size/M
