Repository helm/chartmuseum, pull requests merged in 2022-02, with the labels that each got.

#543 fix: avoid panic with dynamic depth configured
  pkg/chartmuseum/router/match.go
  pkg/chartmuseum/router/match_test.go
Labels: size/S

#544 ci: move building the go binaries outside of the Docker image to speed up builds
  .dockerignore
  .github/workflows/build.yml
  Dockerfile
  scripts/acceptance.sh
  scripts/release-artifacts.sh
Labels: size/M

#553 fix: Use the github API to get the latest release version
  scripts/get-chartmuseum
Labels: size/XS, bug

#554 refactor: remove disablemetrics for enablemetrics
  README.md
  cmd/chartmuseum/main.go
  pkg/config/vars.go
Labels: size/S
