Repository helm/chartmuseum, pull requests merged in 2022-04, with the labels that each got.

#551 feature add chart template and value api
  README.md
  pkg/chartmuseum/server/multitenant/api.go
  pkg/chartmuseum/server/multitenant/handlers.go
  pkg/chartmuseum/server/multitenant/routes.go
  pkg/chartmuseum/server/multitenant/server_test.go
  testdata/charts/mychart/values.yaml
Labels: size/L

#573 pkg/chartmuseum: re-fmt import path
  pkg/chartmuseum/server/multitenant/handlers.go
Labels: size/S

#556 fix: Avoid data races for cacheEntries and index files
  loadtesting/Pipfile
  loadtesting/Pipfile.lock
  loadtesting/locustfile.py
  pkg/chartmuseum/server/multitenant/cache.go
  pkg/chartmuseum/server/multitenant/handlers.go
  pkg/chartmuseum/server/multitenant/index.go
  pkg/chartmuseum/server/multitenant/server.go
  pkg/chartmuseum/server/multitenant/server_test.go
  pkg/repo/index.go
  scripts/test.sh
Labels: size/XL
