Repository helm/chartmuseum, pull requests merged in 2022-01, with the labels that each got.

#489 Correct README description of config file keys
  README.md
Labels: size/S

#482 Update Go dependencies, fix broken tests
  acceptance_tests/lib/ChartMuseum.py
  go.mod
  go.sum
  pkg/chartmuseum/router/router.go
  pkg/chartmuseum/server/multitenant/api.go
  pkg/chartmuseum/server/multitenant/server_test.go
  scripts/acceptance.sh
Labels: size/XXL

#519 pkg/chartmuseum/router: fix potential CRLF log injection by constructing vulnerable request
  pkg/chartmuseum/router/middleware.go
Labels: size/XS

#504 Do not fetch chart content, when not needed
  pkg/chartmuseum/server/multitenant/cache.go
Labels: size/XS

#381 feat(jmespath): add jmespath support
  README.md
  cmd/chartmuseum/main.go
  pkg/chartmuseum/router/router.go
  pkg/chartmuseum/server.go
  pkg/config/vars.go
Labels: size/L

#522 feat: deprecate enforcesemver2 config option
  .gitignore
  acceptance_tests/lib/ChartMuseum.py
  cmd/chartmuseum/main.go
  go.mod
  pkg/chartmuseum/server.go
  pkg/chartmuseum/server/multitenant/api.go
  pkg/chartmuseum/server/multitenant/server_test.go
  pkg/config/vars.go
Labels: size/M

#527 Various v0.14.0 prep items
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  Dockerfile
  Makefile
  README.md
  SECURITY.md
  acceptance_tests/lib/Helm.py
  go.mod
  go.sum
  pkg/chartmuseum/server/multitenant/server_test.go
  scripts/acceptance.sh
  scripts/setup-test-environment.sh
  testdata/badcharts/mybadsemver2chart/.helmignore
  testdata/badcharts/mybadsemver2chart/Chart.yaml
  testdata/badcharts/mybadsemver2chart/templates/pod.yaml
Labels: size/XL

#531 ci: fixes the ghcr login and introduce the image sign mechanism
  .github/workflows/build.yml
Labels: size/S

#533 feat: Add configuration deprecation warning logs
  cmd/chartmuseum/main.go
  pkg/chartmuseum/server.go
  pkg/chartmuseum/server/multitenant/server.go
  pkg/chartmuseum/server_test.go
  pkg/config/config.go
  pkg/config/vars.go
Labels: size/M

#466 Add per chart limit option
  cmd/chartmuseum/main.go
  pkg/chartmuseum/server.go
  pkg/chartmuseum/server/multitenant/api.go
  pkg/chartmuseum/server/multitenant/server.go
  pkg/chartmuseum/server/multitenant/server_test.go
  pkg/config/vars.go
  scripts/setup-test-environment.sh
Labels: size/L

#535 Sign archives and checksums with cosign
  .github/workflows/build.yml
  Makefile
  README.md
  scripts/release-artifacts.sh
  scripts/release-notes.sh
Labels: size/M

#536 Add cbuto to OWNERS
  OWNERS
Labels: size/XS

#538 Generate SPDX SBOM at release time
  .github/workflows/build.yml
  Makefile
  scripts/release-artifacts.sh
  scripts/release-notes.sh
  scripts/sbom.sh
Labels: size/M
