Repository helm/chartmuseum, pull requests merged in 2023-06, with the labels that each got.

#692 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  pkg/chartmuseum/server/multitenant/artifacthub.go
  pkg/chartmuseum/server/multitenant/cache.go
  pkg/chartmuseum/server/multitenant/server_test.go
  pkg/repo/index.go
Labels: size/S

#693 Update various dependencies, prep for 0.16.0 release
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  Makefile
  README.md
  go.mod
  go.sum
  loadtesting/Pipfile.lock
  scripts/setup-test-environment.sh
Labels: size/L

#700 test: Use eventually to avoid flakey test
  pkg/chartmuseum/server/multitenant/server_test.go
Labels: size/M

#701 chore(deps): bump storage to v0.14.0
  go.mod
  go.sum
Labels: size/S

#702 fix: lock tenant map to avoid race
  pkg/chartmuseum/server/multitenant/cache.go
Labels: size/XS

#703 Prep for v0.16.1 release
  Makefile
  README.md
  scripts/setup-test-environment.sh
Labels: size/S
